name: FelinePine
on:
  push:
    branches-ignore:
      - '*WIP'

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    env:
      PACKAGE_NAME: FelinePine
      SWIFT_VER: ${{ matrix.swift-version }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        container:
          - swift:5.8.1-jammy
          - swift:5.8.1-focal
          - swift:5.9-jammy
          - swift:5.9-focal
          - swift:5.10.1-jammy
          - swift:5.10.1-focal
          - swift:6.0.3-jammy
          - swift:6.0.3-focal
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache swift package modules
        id: cache-spm-linux
        uses: actions/cache@v4
        env:
          cache-name: SPM
        with:
          path: .build
          key: ${{ env.cache-name }}-docker-${{ matrix.container }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ env.cache-name }}-docker-${{ matrix.container }}-
            ${{ env.cache-name }}-docker-

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --enable-test-discovery --enable-code-coverage

      - uses: sersoft-gmbh/swift-coverage-action@v4
        id: coverage-files
        with:          
          fail-on-empty-output: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4       
        with:
          fail_ci_if_error: true
          flags: ${{ matrix.container }}
          verbose: true        
          token: ${{ secrets.CODECOV_TOKEN }}  
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }} 
  build-macos:
    name: Build on macOS
    env:
      PACKAGE_NAME: FelinePine
    runs-on: ${{ matrix.runs-on }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.1.app"
          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.2.app"
          
          # iOS Build Matrix
          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.1.app"
            deviceName: "iPhone 16"
            osVersion: "18.1"
          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.2.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.2"
  
          # watchOS Build Matrix
          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.1.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.1"
          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.2.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.2"
  
          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.2.app"
            deviceName: "Apple Vision Pro"
            osVersion: "2.2"
  
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Xcode Name
        run: echo "XCODE_NAME=$(basename -- ${{ matrix.xcode }} | sed 's/\.[^.]*$//' | cut -d'_' -f2)" >> $GITHUB_ENV
      
      - name: Setup Xcode
        run: sudo xcode-select -s ${{ matrix.xcode }}/Contents/Developer
  
      # SPM Cache Step
      - name: Cache swift package modules
        id: cache-spm-macos
        uses: actions/cache@v4
        env:
          cache-name: cache-spm
        with:
          path: .build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
  
      - name: Build SPM
        if: "!matrix.type"
        run: swift build
  
      - name: Run Swift Package tests
        if: "!matrix.type"
        run: swift test -v --enable-code-coverage
  
      - name: Enable Swift Testing
        if: matrix.type
        run: |
          mkdir -p ~/Library/org.swift.swiftpm/security/        
          cp macros.json ~/Library/org.swift.swiftpm/security/    
  
      # Common iOS/watchOS Test Steps
      - name: Run Device Tests
        if: matrix.type
        run: >
          xcodebuild test
          -scheme ${{ env.PACKAGE_NAME }}        
          -sdk ${{ matrix.type == 'ios' && 'iphonesimulator' || matrix.type == 'watchos' && 'watchsimulator' || 'xrsimulator' }}
          -destination 'platform=${{ matrix.type == 'ios' && 'iOS Simulator' || matrix.type == 'watchos' && 'watchOS Simulator' || 'visionOS Simulator' }},name=${{ matrix.deviceName }},OS=${{ matrix.osVersion }}'
          -enableCodeCoverage YES
          build test        
          
      # Common Coverage Steps
      - name: Process Coverage
        uses: sersoft-gmbh/swift-coverage-action@v4
        with:
          fail-on-empty-output: true
  
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.type && format('{0}{1}', matrix.type, matrix.osVersion) || 'spm' }}
